[package]
name = "letsencrypt-inwx"
version = "1.0.2"
description = "A small cli utility for automating the letsencrypt dns-01 challenge for domains hosted by inwx"
authors = ["Matthias Herzog <gh@f8t.eu>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/kegato/letsencrypt-inwx"

[package.metadata.deb]
depends = ""
extended-description = "A small cli utility for automating the letsencrypt dns-01 challenge for domains hosted by inwx. The dns-01 challenge is required for obtaining wildcard certificates from letsencrypt."
assets = [
    ["target/release/letsencrypt-inwx", "usr/bin/", "755"],
    ["etc/certbot-inwx-auth", "usr/lib/letsencrypt-inwx/", "755"],
    ["etc/certbot-inwx-cleanup", "usr/lib/letsencrypt-inwx/", "755"]
]

[dependencies]
sxd-xpath = "^0.4.1"
sxd-document = "^0.2.6"
reqwest = "^0.8.6"
cookie = "^0.10.1"
trust-dns-resolver = "^0.9.0"
clap = "^2.32.0"
openssl-probe = "^0.1.2"